services:

  frontend:
    build:
      context: ./frontend-angular
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    restart: unless-stopped

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: gestion_empleados
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: