services:
  frontend:
    build:
      context: ./frontend-angular
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend-angular/src:/app/src
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src   
    restart: unless-stopped

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: gestion_empleados
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: